name: C2ME Build Script

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 17
        java-package: jdk
        
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ./.gradle/loom-cache
        key: ${{ runner.os }}-gradle4-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle4-
        
    - name: Build C2ME
      run: |
        ./gradlew clean build --stacktrace

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: c2me-artifact
        path: 'build/libs/*.jar'
      
